[OSDEV-913] Updating the submitted claim auto-reply message
opensupplyhub/open-supply-hub pull request #106
Opened 2024-03-18 15:39 UTC by vrwOAR

Updating the text & html files of the claim_facility_submitted email files to align with current recommendations for account creation & to address current functionality that sends emails to the contact from the facility claim request form.

2024-03-20 10:58 UTC, vladsha-dev requested changes
1. I left one comment.
2. There is one more file that needs to be updated: the RELEASE-NOTES.md file. Since these changes will not be included in the 1.10 release, please add a new chapter for version 1.11 to the RELEASE-NOTES.md file. You can find the template for the new version in the RELEASE-NOTES-TEMPLATE.md file.
After adding the new chapter, please update the "What's New" section with your updates. You can refer to examples of how this section is filled for other release versions.
I would write something like this:
[OSDEV-914](https://opensupplyhub.atlassian.net/browse/OSDEV-914) - Update the submitted claim auto-reply message to inform claimants about additional details regarding the expected timeline for review and proactive steps they can take to provide necessary documentation to the claims team.

2024-03-20 10:58 UTC, vladsha-dev commented on src/django/api/templates/mail/claim_facility_submitted_body.txt
> +To complete a claim request, you'll need to submit the following documentation:
Looks like the same text should be added to the HTML template (`claim_facility_submitted_body.html`), doesn't it?
Sorry, if I missed smth.

2024-04-08 11:03 UTC, killev approved these changes

2024-04-08 11:15 UTC, vladsha-dev approved these changes
LGTM

2024-04-08 11:16 UTC, VadimKovalenkoSNF approved these changes
lgtm

2024-04-08 11:21 UTC, merged