Claim: Updating the approved claim auto-reply message
opensupplyhub/open-supply-hub pull request #108
Opened 2024-03-18 15:52 UTC by vrwOAR

Updating the text & html files of the claim_facility_approval email files to advise claimants of the editing behavior that will revoke their claim.

2024-03-20 10:27 UTC, vladsha-dev requested changes
Changes look good to me, but there is one more file that needs to be updated: the `RELEASE-NOTES.md` file.
Since these changes will not be included in the `1.10` release, please add a new chapter for version `1.11` to the `RELEASE-NOTES.md` file. You can find the template for the new version in the `RELEASE-NOTES-TEMPLATE.md` file.
After adding the new chapter, please update the "What's New" section with your updates. You can refer to examples of how this section is filled for other release versions.
I would write something like this:
[OSDEV-914](https://opensupplyhub.atlassian.net/browse/OSDEV-914) - Update the approved claim auto-reply message to inform claimants of their editing parameters. This ensures that claimants are aware and less likely to edit the name and address beyond the approved claim values.

2024-03-20 11:37 UTC, vladsha-dev commented on src/django/api/templates/mail/claim_facility_approval_body.txt
> +You are approved! You can now complete your profile, adding business information including production capabilities, certifications, MOQs and more. The "Facility name (English language)" & "Address" f
I am not sure that it is possible in the `.txt` file...

2024-03-20 11:47 UTC, VadimKovalenkoSNF commented on src/django/api/templates/mail/claim_facility_approval_body.txt
> +You are approved! You can now complete your profile, adding business information including production capabilities, certifications, MOQs and more. The "Facility name (English language)" & "Address" f
Yes, thank you for noticing that.

2024-04-08 11:14 UTC, vladsha-dev approved these changes
LGTM

2024-04-08 11:16 UTC, VadimKovalenkoSNF submitted a review, later dismissed
Approved

2024-04-08 11:25 UTC, vladsha-dev approved these changes
LGTM

2024-04-08 11:25 UTC, VadimKovalenkoSNF approved these changes
Approved

2024-04-08 11:40 UTC, merged