[OSDEV-974] Reporting. Contributor type by %.
opensupplyhub/open-supply-hub pull request #154
Opened 2024-04-09 13:12 UTC by Innavin369

[OSDEV-974](https://opensupplyhub.atlassian.net/browse/OSDEV-974)  Reporting. Contributor type by %.

* Admin see in the report data for the percent of data contributors on the platform by type (this should be in percent format with two decimal places shown), only accounts that have contributed data, the data should be ordered by most recent to oldest month and display mid-month values.

2024-04-09 14:24 UTC, roman-stolar approved these changes
LGTM

2024-04-10 13:56 UTC, VadimKovalenkoSNF commented on doc/release/RELEASE-NOTES.md
> +* [OSDEV-974](https://opensupplyhub.atlassian.net/browse/OSDEV-974) Reporting. Contributor type by %. Admin see in the report data for the percent of data contributors on the platform by type (this s
Fix typo, it should be `Admin sees`

2024-04-10 14:01 UTC, VadimKovalenkoSNF requested changes
Left few comments

2024-04-10 14:01 UTC, VadimKovalenkoSNF commented on src/django/api/reports/contributor_type_by_percent.sql
> +SELECT
I think this query can be optimized, but need other developer to take a look.

2024-04-11 14:28 UTC, VadimKovalenkoSNF commented on src/django/api/reports/contributor_type_by_percent.sql
> +SELECT
Looks better now, thanks

2024-04-11 14:35 UTC, roman-stolar approved these changes
Approved

2024-04-11 18:36 UTC, merged