[OSDEV-788] API user. Incorrect response upon attempting to check for a match.
opensupplyhub/open-supply-hub pull request #212
Opened 2024-05-20 09:25 UTC by roman-stolar

[OSDEV-788](https://opensupplyhub.atlassian.net/browse/OSDEV-788) API user. Incorrect response upon attempting to check for a match.
- Re-written logic for New_Facility/Automatic_Match when we collect & save data for FacilityListItemTemp/FacilityMatchTemp.

2024-05-20 09:25 UTC, roman-stolar commented
Working on possible tests

2024-05-22 13:10 UTC, roman-stolar commented
Team please skip Dedupe Hub App | Unittest test suite - Code coverage report as it didn't showed properly in case of missed init.py files all over the project.

2024-05-23 06:26 UTC, VadimKovalenkoSNF requested changes
Left minor comment.

2024-05-23 06:26 UTC, VadimKovalenkoSNF commented on src/dedupe-hub/api/tests/test_cumulative_matcher.py
> +        self.assertEqual(result_two, {
Use `assertDictEqual` here instead.

2024-05-23 08:45 UTC, roman-stolar commented on src/dedupe-hub/api/tests/test_cumulative_matcher.py
> +        self.assertEqual(result_two, {
Done

2024-05-23 08:59 UTC, VadimKovalenkoSNF approved these changes
Looks good overall, but need other developers to verify.

2024-05-23 09:01 UTC, roman-stolar commented
> But pls, increase codecov issue for DD.

As I mention it an global issue that init.py files missed, so the DD coverage result are wrong.

2024-05-23 09:36 UTC, vladsha-dev commented
> > But pls, increase codecov issue for DD.
> 
> As I mention it an global issue that init.py files missed, so the DD coverage result are wrong.

I suspect the code coverage has decreased because some files were not covered by tests previously, but now they are. It looks like these files weren't fully covered while writing the new tests, which is why it says that the code coverage decreased. So, it requires writing more tests for these specific files, or you can add `__init__.py` files in a separate PR but make this PR dependent on the first one. This way, we will not have this problem in the future with the DD hub, at least.

2024-05-23 09:39 UTC, roman-stolar commented
> I suspect the code coverage has decreased because some files were not covered by tests previously, but now they are. It looks like these files weren't fully covered while writing the new tests, which is why it says that the code coverage decreased. So, it requires writing more tests for these specific files, or you can add **init**.py files in a separate PR but make this PR dependent on the first one. This way, we will not have this problem in the future with the DD hub, at least.

Yes, I will create seperate PR with init.py files for DD and ask to merge them first.
cc @vladsha-dev @VadimKovalenkoSNF

2024-05-23 09:46 UTC, roman-stolar commented
@VadimKovalenkoSNF @vladsha-dev Please review & approve https://github.com/opensupplyhub/open-supply-hub/pull/216

2024-05-23 09:48 UTC, VadimKovalenkoSNF submitted a review, later dismissed
Approved

2024-05-23 13:35 UTC, vladsha-dev approved these changes
LGTM

2024-05-23 13:36 UTC, VadimKovalenkoSNF approved these changes
Lgtm

2024-05-23 13:45 UTC, merged