[OSDEV-939] Facility Claims. New Claims documentation screens.
opensupplyhub/open-supply-hub pull request #232
Opened 2024-06-07 11:15 UTC by roman-stolar

[OSDEV-939](https://opensupplyhub.atlassian.net/browse/OSDEV-939) Facility Claims. New Claims documentation screens.
- Implemented new pages/steps for Facility Claim Request
- Configured basic fields and connected to backend with modification backend data handling
- Updated logic for multiple file uploader component
- Added popup for successfully submitted claim

2024-06-10 13:16 UTC, roman-stolar commented
The changes is ready for review, working on FE tests fixes.

2024-06-11 09:47 UTC, VadimKovalenkoSNF commented on src/react/src/components/ClaimAttachmentsUploader.jsx
> +export default connect()(ClaimAttachmentsUploader);
This became a 'dumb' component now, no need to use `connect()` here

2024-06-11 09:49 UTC, VadimKovalenkoSNF commented on src/react/src/components/ClaimAttachmentsUploader.jsx
> -import PropTypes from 'prop-types';
PropTypes should be present there because you are passing props from parent `ClaimFacilitySupportDocs` component.

2024-06-11 09:50 UTC, VadimKovalenkoSNF commented on src/react/src/components/ClaimAttachmentsUploader.jsx
> -ClaimAttachmentsUploader.defaultProps = {
As I've mentioned before, bring back proptypes.

2024-06-11 09:59 UTC, VadimKovalenkoSNF commented on src/react/src/__tests__/components/ClaimAttachmentsUploader.test.js
> +            <ClaimAttachmentsUploader inputId="files" files={[]} updateUploadFiles={() => {}}/>
You propably don't need `updateUploadFiles={() => {}}` here, but if this prop will obligated in the proptypes, then keep it.

2024-06-11 10:02 UTC, VadimKovalenkoSNF requested changes
Left few comments.

2024-06-11 11:42 UTC, VadimKovalenkoSNF requested changes
Pls, add release notes.

2024-06-11 12:45 UTC, VadimKovalenkoSNF approved these changes
Lgtm

2024-06-11 12:48 UTC, vladsha-dev approved these changes
LGTM

2024-06-11 13:33 UTC, merged