[OSDEV-1004] Update the SQL for gathering data and modify the facility schema to follow the target specification.
opensupplyhub/open-supply-hub pull request #233
Opened 2024-06-07 15:45 UTC by vladsha-dev

2024-06-14 11:40 UTC, mazursasha1990 requested changes
Left some comments.

2024-06-14 11:40 UTC, mazursasha1990 commented on src/logstash/scripts/facilities/facility_type.rb
> +  # Get the facility_type_value (assuming it's a field in the event).
Do we really need those changes here and in other places? I mean adding dots at the end of the comment line.

2024-06-14 11:40 UTC, mazursasha1990 commented on doc/release/RELEASE-NOTES.md
> +* Release date: June 26, 2024
The release date is June 29, 2024. Please, change it.

2024-06-17 08:19 UTC, roman-stolar commented
In general LGTM, didn't see code changes issue directly. Waiting for final version if code changes (without Draft).

2024-06-17 08:21 UTC, vladsha-dev commented
> In general LGTM, didn't see code changes issue directly. Waiting for final version if code changes (without Draft).

Thank you, Roman! I need to make some changes. I will let you know when it is ready.

2024-06-17 15:52 UTC, mazursasha1990 requested changes

2024-06-17 15:52 UTC, mazursasha1990 commented on src/logstash/scripts/facilities/facility_type.rb
> +  # Get the facility_type_value (assuming it's a field in the event).
Do we really need those changes here and in other places? I mean adding dots at the end of the comment line.

2024-06-18 05:15 UTC, VadimKovalenkoSNF commented
> Set up the main Logstash pipeline to run every 15 minutes(agreed with stakeholders).

Could you explain the intention of this?

2024-06-18 05:30 UTC, VadimKovalenkoSNF requested changes
Ask for minor changes

2024-06-18 07:17 UTC, vladsha-dev commented
> > Set up the main Logstash pipeline to run every 15 minutes(agreed with stakeholders).
> 
> Could you explain the intention of this?

To avoid overloading the database with frequent requests, we decided to set a 15-minute gap between each refresh of OpenSearch. Based on Mariel's explanation, this will be sufficient for now since there is no need for facilities to appear in the search in real time.

2024-06-18 12:33 UTC, roman-stolar approved these changes
LGTM, I think we need @protsack-stephan review here.

2024-06-19 07:42 UTC, Innavin369 approved these changes

2024-06-19 07:59 UTC, merged