Remove logstash ECR
opensupplyhub/open-supply-hub pull request #242
Opened 2024-06-12 18:26 UTC by killev

2024-06-13 12:45 UTC, vladsha-dev requested changes
Please update RELEASE-NOTES.md file

2024-06-14 09:58 UTC, vladsha-dev approved these changes
LGTM
Please, mark this PR as ready for review. It is Draft.

2024-06-20 06:58 UTC, roman-stolar approved these changes

2024-06-20 07:02 UTC, VadimKovalenkoSNF approved these changes
Approved

2024-06-20 07:24 UTC, merged