Osdev 273 implement filtering by country and status for claims [FE only]
opensupplyhub/open-supply-hub pull request #288
Opened 2024-07-15 07:38 UTC by VadimKovalenkoSNF

FE part of https://github.com/opensupplyhub/open-supply-hub/pull/262

2024-07-15 10:50 UTC, roman-stolar approved these changes
LGTM

2024-07-15 14:05 UTC, roman-stolar submitted a review, later dismissed

2024-07-16 08:37 UTC, mazursasha1990 requested changes
Added a request to change some names to be more explicit.

2024-07-16 08:47 UTC, mazursasha1990 commented
Please, add relevant description to the PR.

2024-07-16 10:41 UTC, VadimKovalenkoSNF commented on src/react/src/actions/claimFacilityDashboard.jsx
> +        const qs = createQueryStringFromSearchFilters(filters);
Fixed.

2024-07-16 10:41 UTC, VadimKovalenkoSNF commented on src/react/src/components/Filters/ClaimStatusFilter.jsx
> +        s => {
Fixed.

2024-07-16 10:41 UTC, VadimKovalenkoSNF commented on src/react/src/components/Filters/ClaimStatusFilter.jsx
> +        updateClaimStatus: v => dispatch(updateClaimStatusFilter(v)),
Fixed.

2024-07-16 10:46 UTC, mazursasha1990 approved these changes
LGTM

2024-07-16 11:20 UTC, roman-stolar approved these changes

2024-07-16 11:28 UTC, mazursasha1990 approved these changes
LGTM

2024-07-16 11:39 UTC, merged