[OSDEV-1153] Create integration tests for the OpenSearch
opensupplyhub/open-supply-hub pull request #320
Opened 2024-08-12 14:28 UTC by roman-stolar

[OSDEV-1153](https://opensupplyhub.atlassian.net/browse/OSDEV-1153) Create integration tests for the OpenSearch

- Create Integration Tests for OpenSearch

2024-08-20 12:05 UTC, VadimKovalenkoSNF reviewed
Asked few questions.

2024-08-20 14:08 UTC, roman-stolar commented on docker-compose.tests.yml
> +      - USER_API_TOKEN=1d18b962d6f976b0b7e8fcf9fcc39b56cf278051
@VadimKovalenkoSNF Yes, this token is created automatically when we fill database with fixtured data.

2024-08-21 07:32 UTC, VadimKovalenkoSNF commented on scripts/start_local_dev
> +        # Collect Django static files
Got it.

2024-08-21 07:32 UTC, VadimKovalenkoSNF commented on docker-compose.tests.yml
> +      - USER_API_TOKEN=1d18b962d6f976b0b7e8fcf9fcc39b56cf278051
Got it, thanks.

2024-08-21 07:33 UTC, VadimKovalenkoSNF approved these changes
Looks ok, thank you for implementing this.

2024-08-22 07:35 UTC, mazursasha1990 requested changes
In general, looks good to me. 
But I would recommend to rename the file.

2024-08-22 07:35 UTC, mazursasha1990 commented on scripts/start_cq_dev
Please rename this file to `start_code_quality_dev`, because the `cq` is not immediately clear.

2024-08-22 08:55 UTC, roman-stolar commented on scripts/start_cq_dev
@mazursasha1990 Done.

2024-08-22 08:58 UTC, mazursasha1990 approved these changes
LGTM

2024-08-22 08:58 UTC, VadimKovalenkoSNF approved these changes
LGTM

2024-08-22 09:37 UTC, merged