[OSDEV-1045] Change color for claimed facility in merge screen
opensupplyhub/open-supply-hub pull request #335
Opened 2024-08-26 21:47 UTC by Innavin369

[OSDEV-1045](https://opensupplyhub.atlassian.net/browse/OSDEV-1045) Data Moderation. Change the color of the facility panel for claimed facilities in the Merge moderation screens.

2024-08-29 06:14 UTC, VadimKovalenkoSNF requested changes
Can you add frontend unit tests, please?

2024-08-29 08:04 UTC, mazursasha1990 requested changes

2024-08-29 08:14 UTC, mazursasha1990 requested changes
After reviewing your PR, I noticed that the provided solution does not meet the acceptance criteria. Specifically, it incorrectly assigns a green background to facilities that have a claim with 'PENDING' or 'DENIED' status. 
Additionally, I believe there could be a different approach to this implementation. Please contact me directly for a more detailed explanation.

2024-08-29 22:31 UTC, Innavin369 commented on doc/release/RELEASE-NOTES.md
> +* [OSDEV-1045](https://opensupplyhub.atlassian.net/browse/OSDEV-1045) - Data Moderation. Change the color of the facility panel for claimed facilities in the Merge moderation screens.
done

2024-08-30 07:05 UTC, mazursasha1990 requested changes

2024-08-30 07:05 UTC, mazursasha1990 commented on src/react/src/components/DashboardUpdateFacilityLocation.jsx
> +                    highlightBackground={dashboardFacilityMergeCards.includes(
Don't pass highlightBackground if you don't need to change the background for the card in the DashboardDeleteFacility component.

2024-08-30 07:05 UTC, mazursasha1990 commented on src/react/src/util/constants.jsx
> +]);
I believe these changes aren't necessary and you don't need to add them.

2024-08-30 07:05 UTC, mazursasha1990 commented on doc/release/RELEASE-NOTES.md
> +* [OSDEV-1045](https://opensupplyhub.atlassian.net/browse/OSDEV-1045) - The color of the facility panel for claimed facilities in the Merge moderation screens has been changed to green. Added flag `h
Please update the description after implementing the changes according to the comments I provided below.

2024-08-31 13:11 UTC, mazursasha1990 requested changes

2024-08-31 13:11 UTC, mazursasha1990 commented on src/react/src/__tests__/components/DashboardFacilityCard.test.js
> +            },});
I believe that moving the complex prop object into a variable can improve the readability and maintainability of the test.

    const claimedFacilityProps = {
        highlightBackground: true,
        data: {
            ...defaultProps.data,
            properties: {
                ...defaultProps.data.properties,
                is_claimed: true,
            },
        },
    };

    const { container } = renderComponent(claimedFacilityProps);

2024-08-31 13:11 UTC, mazursasha1990 commented on doc/release/RELEASE-NOTES.md
> +* [OSDEV-1045](https://opensupplyhub.atlassian.net/browse/OSDEV-1045) - The color of the facility panel for claimed facilities in the Merge moderation screen has been changed to green. Added flag `hi
> Added flag `highlightBackground` to highlight panel only on the Dashboard Merge Facilities screen.

I think it's not relevant to the "What's new" section.

Also, please describe the changes in the FacilityIndexDetailsSerializer.

2024-09-02 06:52 UTC, VadimKovalenkoSNF approved these changes
Approved from my side.

2024-09-02 10:27 UTC, roman-stolar submitted a review, later dismissed
In general LGTM, please take a look to @mazursasha1990 comment.

2024-09-02 11:12 UTC, mazursasha1990 approved these changes
LGTM

2024-09-02 12:42 UTC, roman-stolar commented
@Innavin369 Please check django tests, I will approve when it passed on CI.

2024-09-02 13:56 UTC, VadimKovalenkoSNF approved these changes
Approved

2024-09-02 14:01 UTC, mazursasha1990 approved these changes
LGTM

2024-09-02 14:01 UTC, merged