[OSDEV-1101] API v1/production-locations. Extend the country object to include alpha-3 code, numeric code, and country name
opensupplyhub/open-supply-hub pull request #336
Opened 2024-08-27 12:54 UTC by roman-stolar

[OSDEV-1101](https://opensupplyhub.atlassian.net/browse/OSDEV-1101) **API v1/production-locations. Extend the country object to include alpha-3 code, numeric code, and country name**
- added countries format json's & connect to country filter method in logstash
- updated dockerfile to copy static-data folder
- updated production-locations index json schema

2024-08-28 09:08 UTC, vladsha-dev requested changes
1. Please validate the alpha-3 code, numeric code, and country name with the stakeholders. I think it is a sensitive matter.
2. Please prepare the changes for the JSON schema of the response for the api/v1/production-locations endpoint in this repository https://github.com/opensupplyhub/open-supply-hub-api-docs.
3. Please cover the country.rb Ruby filter with tests. Here are the docs -> https://www.elastic.co/guide/en/logstash/current/plugins-filters-ruby.html#_testing_the_ruby_script.

2024-08-28 09:27 UTC, roman-stolar commented
@vladsha-dev Thank you, will take a look.

2024-08-28 09:33 UTC, vladsha-dev commented
> @vladsha-dev Thank you, will take a look.

Please make sure that the tests will cause the code quality pipeline to fail if the tests fail. It may require additional configuration.

2024-08-28 10:08 UTC, roman-stolar commented
@vladsha-dev The PR of schema changes -> https://github.com/opensupplyhub/open-supply-hub-api-docs/pull/9

2024-08-28 18:06 UTC, vladsha-dev requested changes

2024-08-28 18:06 UTC, vladsha-dev commented on src/logstash/static-data/country_alpha_3.json
I think you can manage it with a single file to avoid renaming in multiple places(3 JSON files) if we need to update the alpha-2 code for a country
Each entry in the JSON object will look like this:
```
{
     ...,
     ...,
    "UA": {
        "name": "Ukraine",
        "alpha_3": "UKR",
        "numeric": 804
    },
    ...,
}
```

2024-08-29 08:40 UTC, vladsha-dev commented
> @vladsha-dev The PR of schema changes -> [opensupplyhub/open-supply-hub-api-docs#9](https://github.com/opensupplyhub/open-supply-hub-api-docs/pull/9)

Hi @roman-stolar,
Approved that PR.

2024-08-29 09:21 UTC, roman-stolar commented
@vladsha-dev Mariea validate & approve country json files -> https://spdfn.slack.com/archives/C04RGFZC1GW/p1724895732606589?thread_ts=1724839734.080879&cid=C04RGFZC1GW

2024-08-29 09:22 UTC, roman-stolar commented on src/logstash/static-data/country_alpha_3.json
Good point, I will re-work

2024-08-29 10:43 UTC, roman-stolar commented on src/logstash/static-data/country_alpha_3.json
Resolved

2024-08-29 13:14 UTC, roman-stolar commented
@vladsha-dev @VadimKovalenkoSNF @mazursasha1990 The PR is ready for final review.

2024-08-29 13:17 UTC, VadimKovalenkoSNF approved these changes
Preliminary approved. Pls, double check whether search by country code in `api/v1/production-locations` endpoint still working,

2024-08-29 14:37 UTC, vladsha-dev approved these changes
LGTM

2024-08-30 10:33 UTC, merged