[OSDEV-1126] - Implement OS ID search (BE)
opensupplyhub/open-supply-hub pull request #347
Opened 2024-09-04 17:41 UTC by mazursasha1990

[OSDEV-1126](https://opensupplyhub.atlassian.net/browse/OSDEV-1126) - SLC. Implement OS ID search (BE).

2024-09-10 12:36 UTC, VadimKovalenkoSNF requested changes
Left question / few comments.

2024-09-10 12:36 UTC, VadimKovalenkoSNF commented on src/logstash/indexes/production_locations.json
> +        "historical_os_id": {
Use plural name such as `historical_os_id` since this is the array of items.

2024-09-10 14:53 UTC, mazursasha1990 commented on src/django/api/tests/test_opensearch_query_builder.py
> +        self.builder.add_terms('os_id', ['1', '2'])
Changed.

2024-09-11 03:33 UTC, VadimKovalenkoSNF approved these changes
Approved. Pls, ask @nazarkolossandf to go over all v1 endpoints after meging this PR.

2024-09-11 10:59 UTC, roman-stolar approved these changes
LGTM

2024-09-11 11:44 UTC, merged