Increase open search version from 2.13 to 2.17
opensupplyhub/open-supply-hub pull request #383
Opened 2024-10-17 11:57 UTC by killev

2024-10-17 14:16 UTC, vladsha-dev requested changes
1. The version should also be updated in the TF code.
2. Are there any risks associated with updating it?

2024-10-29 13:54 UTC, killev commented
> 2. Are there any risks associated with updating it?

Not sure about risks. I consider them as low, but if we merge now, we have plenty time to test

2024-10-29 14:02 UTC, vladsha-dev requested changes

2024-10-29 14:02 UTC, vladsha-dev commented on docker-compose.yml
> +      - LOG_LEVEL=INFO
It is by default `info`

2024-10-29 17:27 UTC, roman-stolar approved these changes

2024-10-29 17:27 UTC, merged