[OSDEV-1335] Moderation. Deploy new moderation events Logstash pipeline
opensupplyhub/open-supply-hub pull request #387
Opened 2024-10-21 13:46 UTC by vladsha-dev

- The new "moderation events" Logstash pipeline has been configured and implemented to collect moderation event data from the current PostgreSQL database and save it to OpenSearch. This setup allows for fast searches on the moderation events data.
- Fixed the assertion in the test for the `country.rb` filter of the "production locations" Logstash pipeline. The main issue was with the evaluation of statements in the Ruby block. Since only the last statement is evaluated in a Ruby block, all the checks were grouped into one chain of logical statements and returned as a `result` variable at the end.
- Explicitly set the number of shards and the number of replicas for the "production locations" and "moderation events" OpenSearch indexes. Based on the OpenSearch documentation, a storage size of 10–30 GB is preferred for workloads that prioritize low search latency. Additionally, having too many small shards can unnecessarily exhaust memory by storing excessive metadata. Currently, the "production locations" index utilizes 651.9 MB in the Production env, including replicas, while the "moderation events" index is empty. This indicates that one shard and one replica should be sufficient for the "production locations" and "moderation events" indexes.

2024-10-31 11:22 UTC, VadimKovalenkoSNF requested changes
Ask for change about OpenSearch indexation.

2024-10-31 11:40 UTC, roman-stolar commented on deployment/clear_opensearch/clear_opensearch.sh.tpl
> +curl -X DELETE https://$OPENSEARCH_DOMAIN/moderation-events --aws-sigv4 "aws:amz:eu-west-1:es" --user "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY"
Useful

2024-10-31 11:41 UTC, roman-stolar commented on deployment/clear_opensearch/clear_opensearch.sh.tpl
> +sudo rm /mnt/moderation_events_jdbc_last_run
Useful, but optional

2024-10-31 11:41 UTC, roman-stolar commented on src/logstash/indexes/moderation_events.json
> +  ],
I'll resolved.

2024-10-31 11:44 UTC, roman-stolar commented on src/logstash/scripts/moderation_events/country.rb
> +        exact_country = countries[alpha_2_country_code]
Useful, but optional

2024-10-31 11:46 UTC, roman-stolar approved these changes
In general LGTM, just need to covered @VadimKovalenkoSNF and some @coderabbit comments.

2024-10-31 12:54 UTC, vladsha-dev commented on src/logstash/indexes/moderation_events.json
> +        "request_type": {
@VadimKovalenkoSNF 
It is already for filters. The keyword is for exact search. Am I missing something?

2024-10-31 13:09 UTC, vladsha-dev commented on src/logstash/indexes/moderation_events.json
> +        "request_type": {
Did you mean `terms` search? I checked, and it works for that type of OpenSearch query.
I used the following query:
```
{
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "source": [
                            "API",
                            "SLC"
                        ]
                    }
                }
            ]
        }
    }
}
```

2024-10-31 13:19 UTC, VadimKovalenkoSNF commented on src/logstash/indexes/moderation_events.json
> +        "request_type": {
Current query builder is not adapted to build filter queries like that. It should be:

```
{
    "query": {
        "bool": {
            "must": [
                {
                    "terms": {
                        "source.keyword": [
                            "API",
                            "SLC"
                        ]
                    }
                }
            ]
        }
    }
}
```

See (`source.keyword` vs `source`). Basically, the problem here is that we use query builder on top for `production-locations` mapping which introduces some limitations.

2024-10-31 13:46 UTC, vladsha-dev commented on src/logstash/indexes/moderation_events.json
> +        "request_type": {
I believe this is an issue that should be addressed on the query builder side to make that code more adaptive, as it's not optimal to force OpenSearch to index data in both ways. This approach will lead to additional storage consumption within the OpenSearch instance.

2024-10-31 13:47 UTC, VadimKovalenkoSNF commented on src/logstash/indexes/moderation_events.json
> +        "request_type": {
Yes, I think it is better idea to extend query builder like:
`OpenSearchQueryBuilder(OpenSearchQueryBuilderInterface) → ProductionLocationsQueryBuilder | ModerationEventsQueryBuilder`

2024-10-31 13:48 UTC, vladsha-dev commented on src/logstash/indexes/moderation_events.json
> +        "request_type": {
Yeah

2024-10-31 13:49 UTC, VadimKovalenkoSNF submitted a review, later dismissed
Approved, but as Roman mentioned, resolve coderabbit comments.

2024-10-31 16:37 UTC, vladsha-dev commented on src/logstash/sql/sync_moderation_events.sql
> +		id = ame.contributor_id) AS contributor_name,
Done

2024-10-31 17:58 UTC, vladsha-dev commented on src/logstash/indexes/moderation_events.json
> +}
Done

2024-11-01 08:13 UTC, mazursasha1990 requested changes

2024-11-01 09:06 UTC, vladsha-dev commented on src/logstash/config/pipelines.yml
> +  path.config: "/usr/share/logstash/pipeline/sync_moderation_events.conf"
Done

2024-11-01 09:06 UTC, vladsha-dev commented on src/logstash/config/logstash.yml
> +api.enabled: false
Done

2024-11-01 09:09 UTC, vladsha-dev commented on src/logstash/scripts/moderation_events/country.rb
I deleted obvious comments but left several for clarity.

2024-11-01 09:57 UTC, roman-stolar approved these changes
LGTM

2024-11-01 10:00 UTC, mazursasha1990 requested changes

2024-11-01 10:00 UTC, mazursasha1990 commented on src/logstash/sql/sync_moderation_events.sql
> +	ame.updated_at ASC
Please add an empty line.

2024-11-01 10:08 UTC, vladsha-dev commented on src/logstash/sql/sync_moderation_events.sql
> +	ame.updated_at ASC
Done

2024-11-01 10:10 UTC, mazursasha1990 approved these changes
LGTM

2024-11-01 10:39 UTC, VadimKovalenkoSNF approved these changes
Approved.

2024-11-01 10:51 UTC, merged