[OSDEV-1175] Moderation. Moderation Queue Page connect pagination, sorting and filters (integration)
opensupplyhub/open-supply-hub pull request #429
Opened 2024-11-27 14:28 UTC by roman-stolar

[OSDEV-1175](https://opensupplyhub.atlassian.net/browse/OSDEV-1175) Moderation. Moderation Queue Page connect pagination, sorting and filters (integration)

- Integrated getting, paginating, sorting and filtering the moderation events data
- Updated download formats

2024-11-28 09:13 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueueListTable.jsx
> +                                                {cleanedData.country.name}
It couldn't be null

2024-11-28 09:14 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueueListTable.jsx
> +                                            </TableCell>
It couldn't be null

2024-11-28 09:14 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueueListTable.jsx
> +                                            aria-label={`View contribution record for ${cleanedData.name}`}
It couldn't be null

2024-11-28 09:15 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueue.jsx
> +        },
It couldn't be null

2024-11-28 09:16 UTC, roman-stolar commented on src/react/src/reducers/DashboardModerationQueueReducer.js
> +            }),
The logic won't accept it so it fine

2024-11-28 09:16 UTC, roman-stolar commented on src/react/src/util/util.moderationEventsXLSX.js
> +            moderationEvent.cleaned_data.country.name,
It couldn't be null

2024-11-28 09:59 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueue.jsx
>      downloadEventsError: null,
It's already there.

2024-11-28 10:00 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueue.jsx
> +                fetchEvents={fetchEvents}
It's used.

2024-11-28 10:02 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueue.jsx
> +            fetchEvents();
We need to call dispatch even if there isn't date.

2024-11-28 10:03 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueue.jsx
> +            fetchEvents();
We need to call dispatch even if there isn't date.

2024-11-28 10:03 UTC, roman-stolar commented on src/react/src/util/propTypes.js
> +
Done.

2024-12-02 14:12 UTC, roman-stolar commented on src/react/src/components/Dashboard/DashboardModerationQueueListTable.jsx
> +                                    page * pageSize + pageSize,
It's not handled automatically on server side

2024-12-03 10:59 UTC, VadimKovalenkoSNF requested changes
Overall looks good, left one question and one optimization proposal.

2024-12-03 12:25 UTC, roman-stolar commented on src/react/src/util/util.js
> +    `/api/v1/moderation-events/?${qs}&sort_by=${sortBy}&order_by=${orderBy}&from=${
@VadimKovalenkoSNF Yes, for moderation queue. We decided to use searchAfter field for future OS Hub search implementation.

2024-12-03 15:31 UTC, roman-stolar commented on src/react/src/util/util.js
> +    return Object.entries(inputForQueryString)
@VadimKovalenkoSNF Thank's, Done.

2024-12-04 10:18 UTC, VadimKovalenkoSNF approved these changes
Approved.

2024-12-05 10:12 UTC, vladsha-dev approved these changes
LGTM

2024-12-05 10:32 UTC, merged