Fix release notes
opensupplyhub/open-supply-hub pull request #432
Opened 2024-11-28 16:07 UTC by VadimKovalenkoSNF

Remove duplicate section for release 1.26

2024-11-28 16:16 UTC, vladsha-dev requested changes

2024-11-28 16:16 UTC, vladsha-dev commented on doc/release/RELEASE-NOTES.md
Why do we need these release instructions for 1.26?

2024-11-28 16:25 UTC, VadimKovalenkoSNF commented on doc/release/RELEASE-NOTES.md
I've splitted `search_after` into `search_after[value]` and `search_after[id]`. This will require reindexing of the OpenSearch. I took thees instructions from release `1.24`. Or you think they should be in release protocol only?

2024-11-28 16:39 UTC, vladsha-dev commented on doc/release/RELEASE-NOTES.md
- If you are referring to [this PR](https://github.com/opensupplyhub/open-supply-hub/pull/420), then there is no need to clear OpenSearch, because you only updated the Django code and didn't change the index mapping.
- Regarding the updates you made to the `moderation-events` index mapping for the `contributor_id` field, there is no need to clear the index, because the `moderation-events` index has not been created in the production or staging environments. This is due to the fact that the `api_moderationevent` table is empty. That’s how Logstash and OpenSearch work.

2024-11-28 16:41 UTC, vladsha-dev commented on doc/release/RELEASE-NOTES.md
As of now, I think we will need the same instructions as for the 1.25 release.

2024-11-28 16:44 UTC, VadimKovalenkoSNF commented on doc/release/RELEASE-NOTES.md
@vladsha-dev Thanks for clarification, I will update release notes asap.

2024-11-28 16:54 UTC, VadimKovalenkoSNF commented on doc/release/RELEASE-NOTES.md
> +* [OSDEV-1388](https://opensupplyhub.atlassian.net/browse/OSDEV-1388) - The waiter from boto3 cannot wait more than half an hour so we replaced it with our own.
There is only one section named ### Architecture/Environment changes

2024-11-28 16:56 UTC, VadimKovalenkoSNF commented on doc/release/RELEASE-NOTES.md
Pls, re-check. I only left `reindex_database` command because we don't have migrations so far.

2024-12-02 14:43 UTC, roman-stolar approved these changes
LGTM

2024-12-03 11:15 UTC, merged