[OSDEV-1373] SLC. Implement search page for name & address search (FE).
opensupplyhub/open-supply-hub pull request #437
Opened 2024-12-02 14:38 UTC by Innavin369

[[OSDEV-1373] ](https://opensupplyhub.atlassian.net/browse/OSDEV-1373) The tab `Search by Name and Address.` on the Production Location Search screen has been implemented. There are three required properties (name, address, country). The "Search" button becomes clickable after filling out inputs, creates a link with parameters, and allows users to proceed to the results screen.

<img width="400" alt="Screenshot 2024-12-02 at 15 37 57" src="https://github.com/user-attachments/assets/3b6d7435-7fb1-43ee-9957-733810cdbd27">

2024-12-02 18:18 UTC, Innavin369 commented on src/react/src/components/Contribute/SearchByNameAndAddressTab.jsx
> +        validate(inputCountry.label);
changed

2024-12-05 10:43 UTC, Innavin369 commented on src/react/src/components/Filters/StyledSelect.jsx
> +            )}
The label creates an element in the DOM  and if there is no value I have additional padding (I don't need it) and a warning in the browser console. So I decided to make the label optional.

2024-12-05 11:05 UTC, VadimKovalenkoSNF requested changes
Request minor changes.

2024-12-05 11:08 UTC, Innavin369 commented on src/react/src/util/COLOURS.js
> +    RED: '#f44336',
done

2024-12-05 11:12 UTC, Innavin369 commented on src/react/src/components/Contribute/SearchByNameAndAddressTab.jsx
> +    };
changed

2024-12-05 14:14 UTC, VadimKovalenkoSNF commented on src/react/src/__tests__/components/ContributeProductionLocation.test.js
> +        expect(getByText('Search by OS ID')).toBeInTheDocument();
@Innavin369 , could you apply this test case?

2024-12-06 06:30 UTC, VadimKovalenkoSNF commented on src/react/src/__tests__/components/ContributeProductionLocation.test.js
> +        expect(getByText('Search by OS ID')).toBeInTheDocument();
Ok, you can skip tests for Select component.

2024-12-06 08:41 UTC, Innavin369 commented on src/react/src/components/Contribute/SearchByNameAndAddressTab.jsx
> +    }, []);
added dependencies, skipped the rest changes

2024-12-06 08:42 UTC, Innavin369 commented on src/react/src/components/Contribute/SearchByNameAndAddressTab.jsx
> +    ];
done

2024-12-06 08:43 UTC, Innavin369 commented on src/react/src/components/Contribute/SearchByNameAndAddressTab.jsx
> +    };
changed

2024-12-09 09:47 UTC, VadimKovalenkoSNF approved these changes
Approved.

2024-12-09 10:58 UTC, roman-stolar approved these changes
LGTM

2024-12-09 11:27 UTC, merged