[OSDEV-1533] Moderation Decision Date should be N/A if "status_change_date" is absent in object
opensupplyhub/open-supply-hub pull request #468
Opened 2024-12-20 16:10 UTC by Innavin369

[OSDEV-1533](https://opensupplyhub.atlassian.net/browse/OSDEV-1533) - The presentation of the `Moderation Decision Date` in the `Moderation Queue` table has been corrected. If the "status_change_date" is missing in the object, it now displays as "N/A".

<img width="400" alt="Screenshot 2024-12-20 at 17 10 07" src="https://github.com/user-attachments/assets/43202570-90bb-421d-aec9-2782da115081" />

2024-12-20 16:45 UTC, vladsha-dev submitted a review, later dismissed
LGTM

2024-12-23 10:56 UTC, mazursasha1990 requested changes
Can you please modify the test data for this component to cover this case?

2024-12-23 13:49 UTC, mazursasha1990 requested changes

2024-12-23 13:49 UTC, mazursasha1990 commented on src/react/src/__tests__/components/DashboardModerationQueueListTable.test.js
> +        });
This part of the test looks redundant.

2024-12-23 13:52 UTC, Innavin369 commented on src/react/src/__tests__/components/DashboardModerationQueueListTable.test.js
> +        });
removed

2024-12-23 15:52 UTC, mazursasha1990 approved these changes
LGTM

2024-12-26 08:31 UTC, VadimKovalenkoSNF approved these changes
Approved.

2024-12-26 08:34 UTC, mazursasha1990 approved these changes
LGTM

2024-12-26 09:10 UTC, merged