[OSDEV-1365] SLC: Integrate collecting contribution data page
opensupplyhub/open-supply-hub pull request #470
Opened 2024-12-27 12:57 UTC by VadimKovalenkoSNF

Fix [OSDEV-1365](https://opensupplyhub.atlassian.net/browse/OSDEV-1365)

2025-01-23 10:19 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +    }, [pendingModerationEvent]);
This causes other side-effects, for instance multiple success toast component invocation.

![image](https://github.com/user-attachments/assets/e1d61599-79c9-4200-975c-7e3d706f38d4)

2025-01-23 10:58 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                            )}
Fixed.

2025-01-23 10:58 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +    const submitButtonText = submitMethod === 'POST' ? 'Submit' : 'Update';
Done.

2025-01-23 10:59 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +    }, [singleProductionLocationData]);
Done.

2025-01-23 10:59 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/HOC/withProductionLocationSubmit.jsx
> +};
Though I didn't plan to pass extra props to the wrapped component, this might be changed in the future. I've applied the fix.

2025-01-23 11:00 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialogCloseButton.jsx
> +            ) : (
Fixed.

2025-01-23 11:00 UTC, VadimKovalenkoSNF commented on src/react/src/__tests__/components/ProductionLocationDialog.test.js
> +    });
Applied this test case.

2025-01-23 11:01 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialogFields.jsx
> +    };
Good. I refactored this part.

2025-01-23 11:01 UTC, VadimKovalenkoSNF commented on src/react/src/util/util.js
> +};
Good catch. Fixed.

2025-01-23 11:07 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialogFields.jsx
> +    };
Moreover, I split it into smaller functions.

2025-01-23 11:08 UTC, VadimKovalenkoSNF commented on src/react/src/util/util.js
> +};
This is just utiliy function, we prefer not to throw errors on this level.

2025-01-23 11:15 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialogFields.jsx
> +};
1. We use toastify component to render errors.
2. Fixed.
3. Not necessary to make extra loading for the fields component. It will be rendered within Dialog component with all data in place anyway.

2025-01-24 07:22 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +    } = data;
Fixed.

2025-01-24 13:04 UTC, VadimKovalenkoSNF commented on src/react/src/reducers/SearchParametersReducer.js
> +});
Fixed to `address: null`.

2025-01-27 07:56 UTC, VadimKovalenkoSNF commented on src/react/src/__tests__/components/ProductionLocationDialog.test.js
> +    });
This will be checked manually + we don't pass errors down the component explicitly.

2025-01-27 07:57 UTC, VadimKovalenkoSNF commented on src/react/src/__tests__/components/ProductionLocationDialog.test.js
> +        expect(window.getComputedStyle(claimButton).pointerEvents).not.toBe('none');
We can't apply these tests directly to the claim button because it is wrapped into DialogTooltip component.

2025-01-28 07:16 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                <>{claimButton(classes, osID, false)}</>
Fixed.

2025-01-28 11:46 UTC, roman-stolar commented on src/django/api/tests/test_production_locations_create.py
> +            self.assertEqual(len(response_body_dict), 4)
Why the length was changed, due to moderation id?

2025-01-28 11:46 UTC, roman-stolar commented on src/django/api/tests/test_production_locations_create.py
> +        self.assertEqual(len(response_body_dict), 4)
Why the length was changed, due to moderation id?

2025-01-28 11:49 UTC, VadimKovalenkoSNF commented on src/django/api/tests/test_production_locations_create.py
> +            self.assertEqual(len(response_body_dict), 4)
Because we introduced additional parameter in the response object (e.g .`cleaned_data`)

2025-01-28 11:49 UTC, VadimKovalenkoSNF commented on src/django/api/tests/test_production_locations_create.py
> +        self.assertEqual(len(response_body_dict), 4)
Because we introduced additional parameter in the response object (e.g .cleaned_data)

2025-01-28 12:01 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialogFields.jsx
> +    const formatLabel = key =>
I was also thinking about this, but we won't have any other component so far that will reuse this logic.

2025-01-28 12:07 UTC, roman-stolar commented on src/react/src/components/Contribute/SearchByNameAndAddressSuccessResult.jsx
> +            const baseUrl = `/contribute/production-location/${productionLocation.os_id}/info/`;
Maybe more this url to constant as they also used in SearchByOsIdSuccessResult.
Easy way to split between two constants /contribute/production-location/ and /info/

2025-01-28 12:09 UTC, roman-stolar reviewed
In general LGTM, added some minor question/suggestion.

2025-01-28 13:12 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/SearchByNameAndAddressSuccessResult.jsx
> +            const baseUrl = `/contribute/production-location/${productionLocation.os_id}/info/`;
Done, pls check.

2025-01-28 13:30 UTC, roman-stolar submitted a review, later dismissed
Approved

2025-01-28 13:30 UTC, roman-stolar commented on src/react/src/components/Contribute/SearchByNameAndAddressSuccessResult.jsx
> +            const baseUrl = `/contribute/production-location/${productionLocation.os_id}/info/`;
Great!

2025-01-29 08:59 UTC, VadimKovalenkoSNF commented on src/react/src/util/util.js
> +};
No need, this will be pre-parsed already.

2025-01-29 09:22 UTC, VadimKovalenkoSNF commented on src/react/src/util/util.js
> +};
I refactored it based on your suggestion.

2025-01-29 15:05 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +        ) {
Fixed.

2025-01-29 15:07 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
>  );
Fixed.

2025-01-30 15:05 UTC, vladsha-dev submitted a review, later dismissed
LGTM

2025-01-30 16:47 UTC, mazursasha1990 requested changes

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                onClick={() => history.push(mainRoute)}
Please create a function that handles routing.
`onClick={handle...}`

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                }}
Please create a function that handles routing.
`onClick={handle...}`

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationDialogCloseButton.jsx
> +    const { isMobile, classes, handleShow } = props;
Please wrap the `ProductionLocationDialogCloseButton` component with `withStyles` during the export and destructure props in the function parameters.

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationDialogCloseButton.jsx
> +};
Please add `classes` to propTypes.

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +        if (showProductionLocationDialog === false) {
Please use `if (!showProductionLocationDialog)`.

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +                                handleProductionLocation(data, osID);
Can you simplify the onClick by moving the data object outside?

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/SearchByNameAndAddressNotFoundResult.jsx
> +                    }
Please create a function that handles routing.
onClick={handle...}

2025-01-30 16:47 UTC, mazursasha1990 commented on src/react/src/components/Contribute/SearchByOsIdSuccessResult.jsx
> +                }}
Please create a function that handles routing.
secondaryButtonAction={handle...}

2025-01-31 05:29 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +        if (showProductionLocationDialog === false) {
This won't work in this case. I need the initial state of `showProductionLocationDialog` to be `null` on the first render, then toggle between `true` and `false`. Both `null` and `false` are necessary for proper handling: `null` for the first render and `true` or `false` for subsequent re-renders.

2025-01-31 05:30 UTC, VadimKovalenkoSNF commented on src/react/src/App.css
> +
`withStyles` won't work with `!important` keyword which is required here to override MUI styles for mobile.

2025-01-31 07:38 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/SearchByOsIdSuccessResult.jsx
> +                }}
I've applied separate functions.

2025-01-31 07:38 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/SearchByNameAndAddressNotFoundResult.jsx
> +                    }
I've applied separate functions.

2025-01-31 07:38 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +                                handleProductionLocation(data, osID);
Done.

2025-01-31 07:38 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialogCloseButton.jsx
> +};
Done.

2025-01-31 07:38 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                    {address || 'N/A'}
Good catch, fixed.

2025-01-31 07:39 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                    {productionLocationName || 'N/A'}
Fixed.

2025-01-31 07:39 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +            if (typeof value === 'object' && value !== null) {
I refactored this part, thank you.

2025-01-31 07:39 UTC, VadimKovalenkoSNF commented on src/react/src/util/util.js
> +export const makeGetProductionLocationURL = (osID = '') => {
I renamed this method, pls check.

2025-01-31 07:40 UTC, mazursasha1990 commented on src/react/src/App.css
> +
Okay.
Thank you.

2025-01-31 07:43 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +        if (showProductionLocationDialog === false) {
Okay.
Thank you.

2025-01-31 07:51 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                            })}
This is needed for proper triggering tooltip inside icon.

2025-01-31 08:15 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                            )}
Done.

2025-01-31 08:15 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                                MODERATION_STATUSES_ENUM.PENDING ? (
Done.

2025-01-31 08:15 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                onClick={() => history.push(mainRoute)}
Done.

2025-01-31 08:15 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                }}
Done

2025-01-31 08:16 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                MODERATION_STATUSES_ENUM.PENDING ? (
Done.

2025-01-31 08:52 UTC, mazursasha1990 commented on src/react/src/components/Contribute/ProductionLocationDialog.jsx
> +                                            })}
Okay.
Thank you.

2025-01-31 11:20 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +    },
Fixed.

2025-01-31 11:22 UTC, vladsha-dev submitted a review, later dismissed
LGTM
Great work!

2025-01-31 11:32 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +                        singleModerationEventItem?.cleaned_data
Not necessary to do this check here, as we verify localstorage item presence in 'if' condition on line 754.

2025-01-31 11:43 UTC, VadimKovalenkoSNF commented on src/react/src/components/Contribute/ProductionLocationInfo.jsx
> +    ]);
Fixed.

2025-01-31 12:11 UTC, mazursasha1990 approved these changes
LGTM

2025-01-31 12:19 UTC, vladsha-dev approved these changes
LGTM

2025-01-31 12:20 UTC, merged