[OSDEV-494] List upload: List uploads in the "PENDING" status are being displayed on the Contributor Profile page
opensupplyhub/open-supply-hub pull request #6
Opened 2024-02-06 11:55 UTC by roman-stolar

[OSDEV-494](https://opensupplyhub.atlassian.net/browse/OSDEV-494) List upload: List uploads in the "PENDING" status are being displayed on the Contributor Profile page
- Filter facility list data that sent to User Profile by status equal APPROVED

2024-02-06 15:51 UTC, killev commented on src/django/api/serializers/user/user_profile_serializer.py
> +                    status=FacilityList.APPROVED,
@roman-stolar , Frankly saying I doubt that only approved need to be shown. It's not clear from the task. Let's clarify with @mariel-oar

2024-02-06 15:52 UTC, killev requested changes
In general it looks good. but I'm not sure this is what really expected to be implemented in the original issue.

2024-02-06 15:59 UTC, killev approved these changes
LGTM.

2024-02-07 09:34 UTC, VadimKovalenkoSNF approved these changes
Approved

2024-02-07 09:35 UTC, merged