[OSDEV-693] Implement a GitHub action that applies migrations on given environment
opensupplyhub/open-supply-hub pull request #60
Opened 2024-03-04 14:57 UTC by Innavin369

2024-03-04 15:57 UTC, killev requested changes
Please add information to RELEASE-NOTES

2024-03-04 16:10 UTC, vladsha-dev requested changes
1. I left one comment.
2. There are two more files where changes need to be made. See the screenshot.

<img width="769" alt="Screenshot 2024-03-04 at 17 06 52" src="https://github.com/opensupplyhub/open-supply-hub/assets/58369841/a63961e8-864b-40f0-b105-8f13d0f149cb">

2024-03-04 16:10 UTC, vladsha-dev commented on src/django/oar/settings.py
> +if ENVIRONMENT in ["Production", "Staging", "Prestaging"] and BATCH_MODE == "":
Let's delete Prestaging.

2024-03-04 17:16 UTC, killev approved these changes
LGTM. Approved

2024-03-05 09:55 UTC, vladsha-dev approved these changes
LGTM

2024-03-05 10:29 UTC, merged