[OSDEV-862] Create anonymizer script in docker
opensupplyhub/open-supply-hub pull request #62
Opened 2024-03-04 18:58 UTC by VitalyyP

Create anonymize script in scripts, create anonymizer with scripts and docker-compose.yml

2024-03-05 18:33 UTC, killev commented on anonymizer/scripts/anonymize
> +SQL_SCRIPT="DO \$\$
It would be great to copy this script into docker image.

2024-03-05 18:34 UTC, killev commented on anonymizer/scripts/anonymize
> +docker exec -it anonymize_database-1 psql -U anondb -d anondb -c "$SQL_SCRIPT" && sudo docker exec -it anonymize_database-1 pg_dump -U anondb -d anondb -f ../db_after/anonymized_dump.dump
Copy script that anonymise database to the Docker image

2024-03-05 18:34 UTC, killev commented on scripts/anonymize
> +cd anonymizer || exit
This is weird, I don't understand why is't needed

2024-03-05 18:35 UTC, killev commented on anonymizer/scripts/run_commands.sh
> +./scripts/anonymize
Why we need this? I believe everything should be run inside the container/image

2024-03-05 18:37 UTC, killev requested changes
-1
Name of PR is inaccurate.
I few comments regarding implementation added

2024-04-08 17:26 UTC, killev submitted a review, later dismissed

2024-04-09 07:17 UTC, vladsha-dev requested changes
1. Please, update the branch to the top of the parent branch.
2. Please complete the release notes file.

2024-04-09 10:06 UTC, vladsha-dev approved these changes

2024-04-09 10:08 UTC, killev approved these changes

2024-04-09 10:11 UTC, merged