[OSDEV-644] Error when trying to delete a facility with only one contributor
opensupplyhub/open-supply-hub pull request #82
Opened 2024-03-08 11:21 UTC by roman-stolar

[OSDEV-644](https://opensupplyhub.atlassian.net/browse/OSDEV-644) Error when trying to delete a facility with only one contributor
- Implemented logic to ensure that when we delete a facility, we also clear the corresponding data in the api_facilityclaimreviewnote table.
- Added tests

2024-03-08 12:30 UTC, killev approved these changes
Approved

2024-03-11 10:03 UTC, vladsha-dev requested changes
Please, add a release note as well.

2024-03-11 10:03 UTC, vladsha-dev commented on src/django/api/views/facility/facilities_view_set.py
> +            delete_facility_claim_review_notes(claim)
It is not efficient to execute two identical loops. I believe you can perform this action within the second loop.
```
        for claim in claims:
            delete_facility_claim_review_notes(claim)
            claim._change_reason = f'Deleted {facility.id}'
            claim.delete()
```

2024-03-11 10:06 UTC, vladsha-dev commented on src/django/api/views/facility/facilities_view_set.py
> +                claim_review_note._change_reason = f'Deleted {facility.id}'
Is it for the historical table?

2024-03-11 10:07 UTC, VadimKovalenkoSNF submitted a review, later dismissed
Pls, update RELEASE-NOTES as well.

2024-03-11 10:11 UTC, vladsha-dev requested changes

2024-03-11 10:11 UTC, vladsha-dev commented on src/django/api/views/facility/facilities_view_set.py
> +        def delete_facility_claim_review_notes(claim):
This function can be optimized.
```
def delete_facility_claim_review_notes(claim):
    FacilityClaimReviewNote.objects.filter(claim=claim).update(_change_reason=f'Deleted {claim.facility.id}')
    FacilityClaimReviewNote.objects.filter(claim=claim).delete()
```
By combining the update and delete operations into a single query, we can optimize the code and reduce the number of database queries executed.

2024-03-11 11:28 UTC, roman-stolar commented on src/django/api/views/facility/facilities_view_set.py
> +                claim_review_note._change_reason = f'Deleted {facility.id}'
Yes.

2024-03-12 10:11 UTC, vladsha-dev approved these changes
LGTM

2024-03-12 10:41 UTC, killev approved these changes
LGTM. Approved

2024-03-12 10:42 UTC, merged