Abstract serializer methods to related classes
opensupplyhub/open-supply-hub pull request #88
Opened 2024-03-13 11:57 UTC by VadimKovalenkoSNF

Fix [OSDEV-938](https://opensupplyhub.atlassian.net/browse/OSDEV-938)

2024-03-15 10:17 UTC, vladsha-dev submitted a review, later dismissed
LGTM

2024-03-15 12:36 UTC, vladsha-dev approved these changes
LGTM

2024-03-17 15:54 UTC, vladsha-dev requested changes

2024-03-17 15:54 UTC, vladsha-dev commented on src/django/contricleaner/lib/parsers/file_parser.py
> +    Interface FileParser for parsers related to file parsing.
I realized that it is still an abstract class since it has implemented the `__init__` method. Please, leave the description as it was.

2024-03-18 08:06 UTC, vladsha-dev approved these changes
LGTM

2024-03-18 10:32 UTC, roman-stolar approved these changes
LGTM

2024-03-18 10:59 UTC, merged